apiVersion: v1
kind: ServiceAccount
metadata:
  name: arc-secret-sync
  namespace: arc-runners
  annotations:
    azure.workload.identity/client-id: "__SECRET_SYNC_CLIENT_ID__"
    azure.workload.identity/tenant-id: "__TENANT_ID__"
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: arc-runner
  namespace: arc-runners
  annotations:
    azure.workload.identity/client-id: "__RUNNER_CLIENT_ID__"
    azure.workload.identity/tenant-id: "__TENANT_ID__"
automountServiceAccountToken: false
